name: Wrapper generation

on:
  push:
    branches: [main]
    paths: ['spec.yaml']
  workflow_dispatch:

jobs:
  trigger-wrappers:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger PHP Wrapper
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
          repository: BuiltByBit/api-wrapper-codegen-php
          event-type: spec-updated